[advisories]
ignore = ["RUSTSEC-2025-0141"]

[licenses]
allow = [
  "MIT",
  "Apache-2.0",
  "ISC",
  "BSD-3-Clause",
  "BSD-2-Clause",
  "Unicode-3.0",
  "Unicode-DFS-2016",
]

[bans]
multiple-versions = "deny"

[sources]
allow-git = []
